- name: Get home directory for install user
  user:
    name: "{{ ansible_pull_username }}"
    state: present
  register: ansible_account
  when: not ansible_pull_create_user

- name: Ensure SSH dir is present
  file:
    path: "{{ ansible_account['home'] }}/.ssh"
    owner: "{{ ansible_pull_username }}"
    group: "{{ ansible_pull_username }}"
    state: directory
  when: ansible_pull_create_ssh_key and not ansible_pull_create_user

- name: Create SSH key
  openssh_keypair:
    mode: 0600
    path: "{{ ansible_account['home'] }}/.ssh/ansible_deploy_key"
    owner: "{{ ansible_pull_username }}"
    group: "{{ ansible_pull_username }}"
    comment: "ansible-generated"
    type: ed25519
    state: present
  when: ansible_pull_create_ssh_key and not ansible_pull_create_user
  register: ansible_pull_created_ssh_key
