- name: Create log dir
  file:
    path: "{{ ansible_pull_log_path | dirname }}"
    mode: 0750
    state: directory

- name: Create logrotate entry
  template:
    src: logrotate_ansible_pull.j2
    dest: '/etc/logrotate.d/ansible_pull'
    owner: root
    group: root
    mode: 0644
  when: ansible_pull_logs_rotate
  become: true
