all:
  children:
    ubuntu:
      vars:
        ansible_python_interpreter: /usr/bin/python3
    debian:
      vars:
        ansible_python_interpreter: /usr/bin/python3
    centos:
      children:
        centos_7:
          vars:
            ansible_python_interpreter: /usr/bin/python
        centos_8:
          vars:
            ansible_python_interpreter: /usr/bin/python3
  vars:
    ansible_pull_extra_packages:
      proxmoxer: 1.0.3
    ansible_pull_username: elbisna
    ansible_pull_inventory: inventory.yml
    ansible_pull_playbook: playbook_encrypted.yml
    ansible_pull_repo_url: file:///tmp/ansible-repo
    # Vault passphrase for the encrypted playbook
    ansible_pull_vaults:
      test: ansiblepull
