- name: Create user
  hosts: all
  tasks:
    - name: Create Ansible group
      group:
        name: "{{ ansible_pull_username }}"
        state: present
    - name: Create Ansible user
      user:
        append: true
        comment: To run Ansible in pull mode
        create_home: true
        name: "{{ ansible_pull_username }}"
        group: "{{ ansible_pull_username }}"
        groups: "{{ ansible_pull_username }}"
        shell: /bin/bash
        home: "{{ ansible_pull_install_dir }}"
        generate_ssh_key: false
        state: present
        system: true
      register: ansible_account

- import_playbook: prepare.yml
